#ifndef QSTRUCTUTILITY_EXPORT_H
#define QSTRUCTUTILITY_EXPORT_H

#include <QtGlobal>

#ifdef BUILD_SHARED_WIN
    #ifdef BUILD_QSTRUCTUTILITY_LIB
        #define EXPORT_QSTRUCTUTILITY_LIB_OPT Q_DECL_EXPORT
    #else
        #define EXPORT_QSTRUCTUTILITY_LIB_OPT Q_DECL_IMPORT
    #endif
#else
    #define EXPORT_QSTRUCTUTILITY_LIB_OPT
#endif

#endif // QSTRUCTUTILITY_EXPORT_H
